version: '3.8'
services:
  db:
    image: mysql:8
    env_file:
    - .env
    ports:
    - 3306:3306

  migrate:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    depends_on:
    - db
    volumes:
    - ./migrations:/migrations
    env_file:
    - .env
    environment:
      DB_URL: $MYSQL_USER:$MYSQL_PASSWORD@tcp(db:3306)/$MYSQL_DATABASE

  service:
    build:
      context: .
      dockerfile: service.Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
    - 80:80
