version: '3.8'
services:
  db:
    image: mysql:8
    env_file:
    - .env
    command: --default-authentication-plugin=mysql_native_password

  db_proxy:
    image: proxysql/proxysql
    depends_on:
      - db
      - db_proxy_init
    ports:
    - 6032:6032
    - 6033:6033
    entrypoint: proxysql -f -c /etc/proxysql/proxysql.cnf
    volumes:
    - proxysqlcnf:/etc/proxysql

  db_proxy_init:
    image: hairyhenderson/gomplate
    volumes:
    - ./conf/proxysql.cnf.templ:/proxysql/cnf.templ
    - proxysqlcnf:/proxysql
    env_file:
      - .env
    command: -f /proxysql/cnf.templ -o /proxysql/proxysql.cnf

  migrate:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    depends_on:
    - db
    volumes:
    - ./migrations:/migrations
    env_file:
    - .env
    environment:
      DB_URL: $MYSQL_USER:$MYSQL_PASSWORD@tcp(db_proxy:$PROXY_USER_PORT)/$MYSQL_DATABASE

  service:
    build:
      context: .
      dockerfile: service.Dockerfile
    depends_on:
      - db_proxy
    env_file:
      - .env
    ports:
    - 80:80

volumes:
  proxysqlcnf: