version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=social_network
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
    - 3306:3306

  migrate:
    image: migrate/migrate
    depends_on:
    - db

    volumes:
    - ./migrations:/migrations

    command:
      [ "-path", "/migrations/", "-database",  "mysql://user:password@tcp(db:3306)/social_network", "up" ]
