version: '3.8'
services:
  db:
    image: mysql:8
    env_file:
    - .env
    command: --default-authentication-plugin=mysql_native_password

  db_proxy:
    image: proxysql/proxysql
    depends_on:
      - db
    ports:
    - 6032:6032
    - 6033:6033
    volumes:
    - ./conf/proxysql.cnf:/etc/proxysql.cnf

  db_proxy_init:
    build:
      context: .
      dockerfile: proxysql_init.Dockerfile
    depends_on:
      - db_proxy
    env_file:
      - .env

  migrate:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    depends_on:
    - db
    volumes:
    - ./migrations:/migrations
    env_file:
    - .env
    environment:
      DB_URL: $MYSQL_USER:$MYSQL_PASSWORD@tcp(db:3306)/$MYSQL_DATABASE

  service:
    build:
      context: .
      dockerfile: service.Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
    - 80:80
