name: ci
on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: setup env
        run: |
          make install
      - name: lint
        uses: golangci/golangci-lint-action@v2
      - name: start env
        run: |
          make env
      - name: test-full
        run: |
          make test-full
      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
